import type { MatchRelationType } from '@/data/match-types'
import { matchTypeLabel } from '@/data/match-types'
import type { MatchResult } from '@/data/matching-mock'
import { formatDateShort, formatTime12 } from '@/utils/format'

export type MatchReportKind = 'basic' | 'detailed'

function safeFilePart(value: string): string {
  return value.replace(/[^\w\-]+/g, '-').replace(/^-|-$/g, '') || 'match'
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function personLine(result: MatchResult, who: 'a' | 'b'): string {
  const p = result[who]
  return `${p.name} | ${formatDateShort(p.details.date)} | ${formatTime12(p.details.time)} | ${p.moonRashi} | ${p.moonNakshatra}`
}

function buildLines(
  result: MatchResult,
  matchType: MatchRelationType | null,
  kind: MatchReportKind,
): string[] {
  const typeLabel = matchType ? matchTypeLabel(matchType) : 'Guna Milan'
  const lines: string[] = [
    'Cyklos - Kundli Matching',
    `${typeLabel} match report`,
    kind === 'basic' ? 'Basic summary (free)' : 'Detailed report',
    '',
    `Score: ${result.total} of ${result.max}`,
    '',
    'Person 1',
    personLine(result, 'a'),
    '',
    'Person 2',
    personLine(result, 'b'),
    '',
    'Summary',
    result.summary,
  ]

  if (kind === 'detailed') {
    lines.push(
      '',
      'Note',
      result.caveat,
      '',
      'The eight kootas',
      ...result.kootas.flatMap((k) => [
        `${k.name}: ${k.score} / ${k.max} - ${k.detail}${k.concern ? ` (${k.concern})` : ''}`,
      ]),
      '',
      'Where it holds',
      ...(result.strengths.length
        ? result.strengths.map((k) => `- ${k.name}: ${k.detail}`)
        : ['- None at full marks']),
      '',
      'Where it rubs',
      ...(result.frictions.length
        ? result.frictions.map((k) => `- ${k.name}: ${k.concern ?? k.detail}`)
        : ['- None falling badly short']),
      '',
      'Manglik',
      result.manglik.note,
    )
  } else {
    lines.push(
      '',
      'This basic report includes the total and both charts.',
      'Pay for the detailed PDF to unlock the full eight-koota breakdown.',
    )
  }

  lines.push('', `Generated by Cyklos - ${new Date().toLocaleString()}`)
  return lines
}

/**
 * Minimal single-page PDF from plain text lines (no external PDF library).
 */
function linesToPdfBlob(lines: string[]): Blob {
  const contentLines = [
    'BT',
    '/F1 11 Tf',
    '50 780 Td',
    '14 TL',
    ...lines.flatMap((line, index) => {
      const safe = escapePdfText(line)
      if (index === 0) return [`(${safe}) Tj`]
      return ['T*', `(${safe}) Tj`]
    }),
    'ET',
  ]
  const stream = contentLines.join('\n')
  const objects = [
    '1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj\n',
    '2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj\n',
    '3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>endobj\n',
    `4 0 obj<< /Length ${stream.length} >>stream\n${stream}\nendstream\nendobj\n`,
    '5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj\n',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = [0]
  for (const object of objects) {
    offsets.push(pdf.length)
    pdf += object
  }
  const xrefStart = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
  pdf += `startxref\n${xrefStart}\n%%EOF`

  return new Blob([pdf], { type: 'application/pdf' })
}

export function matchReportFilename(
  result: MatchResult,
  kind: MatchReportKind,
): string {
  const a = safeFilePart(result.a.name)
  const b = safeFilePart(result.b.name)
  return `cyklos-${kind}-match-${a}-${b}.pdf`
}

export function createMatchReportPdfBlob(
  result: MatchResult,
  matchType: MatchRelationType | null,
  kind: MatchReportKind,
): Blob {
  return linesToPdfBlob(buildLines(result, matchType, kind))
}

export function downloadMatchReportPdf(
  result: MatchResult,
  matchType: MatchRelationType | null,
  kind: MatchReportKind,
): string {
  const blob = createMatchReportPdfBlob(result, matchType, kind)
  const filename = matchReportFilename(result, kind)
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
  return filename
}
